# 20.9 — Exception specifications and noexcept

(h/t to reader Koe for providing the first draft of this lesson!)

In C++, all functions are classified as either **non-throwing** (do not throw exceptions) or **potentially throwing** (may throw an exception).

在C++中，所有的函数都可以分为不会抛出异常的和可能会抛出异常的。

Consider the following function declaration:

思考下面的函数声明

```
int doSomething(); // can this function throw an exception or not?
```

Looking at a typical function declaration, it is not possible to determine whether a function might throw an exception or not. While comments may help enumerate whether a function throws exceptions or not (and if so, what kind of exceptions), documentation can grow stale and there is no compiler enforcement for comments.

看着这样的一个函数声明。你没办法知道他到底会不会抛出一个异常。尽管注释可能会帮助提及到底会不会抛出异常。但是文档可能会过时，而且编译器对注释也没有约束力。

**Exception specifications** are a language mechanism that was originally designed to document what kind of exceptions a function might throw as part of a function specification. While most of the `exception specifications` have now been deprecated or removed, one useful `exception specification` was added as a replacement, which we’ll cover in this lesson.

**Exception specifications** 是一个语言机制。最初是为了把函数可能抛出的异常作为函数标准的一部分。尽管现在已经弃用或删除了大多数 **Exception specifications** ，但还是添加了一个有用的 **Exception specifications** 作为替代，我们将在本课程中介绍。

## The noexcept specifier 说明符 noexcept 

The **noexcept specifier** defines a function as `non-throwing`. To define a function as `non-throwing`, we can use the `noexcept` specifier in the function declaration, placed to the right of the function parameter list:

noexcept 定义了一个函数是不会抛出异常的。要定义函数是不会抛出异常的话，我们可以把它放在函数参数列表的右边。

```
void doSomething() noexcept; // this function is non-throwing
```

Note that `noexcept` doesn’t actually prevent the function from throwing exceptions or calling other functions that are `potentially throwing`. Rather, when an exception is thrown, if an exception exits a `noexcept` function, `std::terminate` will be called. And note that if `std::terminate` is called from inside a `noexcept` function, stack unwinding may or may not occur (depending on implementation and optimizations), which means your objects may or may not be destructed properly prior to termination.

注意“ noexcept”实际上并不能阻止该函数引发异常或调用可能潜在引发的其他函数。如果一个声明为noexcept的函数抛出了一个异常，那么std::terminate会被调用。注意这个函数是在noexcept函数中调用的，所以栈展开可能发生也可能不发生（取决于实现和优化），这意味你的对象在被终止前有可能成功析构，也有可能没有成功析构（如果发生栈展开，应该旧栈上的变量应该是成功析构了）。

Much like functions that differ only in their return values can not be overloaded, functions differing only in their exception specification can not be overloaded.

**就像函数的签名不包括返回类型一样，函数的签名同样也不包括它们的异常规范的东西（noexcept）**

## The noexcept specifier with a Boolean parameter

The `noexcept` specifier has an optional Boolean parameter. `noexcept(true)` is equivalent to `noexcept`, meaning the function is `non-throwing`. `noexcept(false)` means the function is potentially throwing. These parameters are typically only used in template functions, so that a template function can be dynamically created as `non-throwing` or `potentially throwing` based on some parameterized value.

noexcept说明符有一个参数，可以填true，也可以填false，如果填ture，和不写参数输出一样的。如果填false，那么意味着这个函数有可能抛出异常。这些参数通常只在模板函数中使用。所以一个模板函数可以在实例化的时候，定义为是不会抛出异常的函数类型，也可以定义为是有可能抛出异常的函数类型。

## Which functions are non-throwing and potentially-throwing

Functions that are `non-throwing` by default:

**默认不会抛出异常的函数们：**

- default constructors
- copy constructors
- move constructors
- destructors
- copy assignment operators
- move assignment operators

However, if any of the listed functions call (explicitly or implicitly) another function which is `potentially throwing`, then the listed function will be treated as `potentially throwing` as well. For example, if a class has a data member with a `potentially throwing` constructor, then the class’s constructors will be treated as `potentially throwing` as well. As another example, if a copy assignment operator calls a `potentially throwing` assignment operator, then the copy assignment will be `potentially throwing` as well.

然而，如果列表中的任何函数调用了可能抛出异常的函数，那么这个函数也会成为可能抛出异常的函数。举个例子，如果一个类的成员的构造函数有可能抛出异常，那么这个类的构造函数也会被看作是可能抛出异常来对待。再举一个例子，如果拷贝赋值运算符重载函数调用了一个可能抛出异常的函数，那么这个重载也会成为可能抛出异常的函数。

```
#### Best practice

If you want any of the above listed functions to be non-throwing, explicitly tag them as `noexcept` (even though they are defaulted that way), to ensure they don’t inadvertently become `potentially throwing`.
```

The following are `potentially throwing` by default:

下面的几个函数被默认认为是可能抛出异常的

- Normal functions

  普通函数 

- User-defined constructors

  用户定义的构造函数

- Some operators, such as `new`

  一些运算符

## **The noexcept operator**

The `noexcept` operator can be used inside functions. It takes an expression as an argument, and returns `true` or `false` if the compiler thinks it will throw an exception or not. The `noexcept` operator is checked statically at compile-time, and doesn’t actually evaluate the input expression.

noexcept 操作符可以在函数中使用。它接受一个表达式作为参数，返回一个布尔值，表示编译器是否觉得这个函数会抛出一个异常。noexcept操作符是在编译时静态检查的。事实上也不会真的去计算传入的表达式。

```
void foo() {throw -1;}
void boo() {};
void goo() noexcept {};
struct S{};
 
constexpr bool b1{ noexcept(5 + 3) }; // true; ints are non-throwing
constexpr bool b2{ noexcept(foo()) }; // false; foo() throws an exception
constexpr bool b3{ noexcept(boo()) }; // false; boo() is implicitly noexcept(false)
constexpr bool b4{ noexcept(goo()) }; // true; goo() is explicitly noexcept(true)
constexpr bool b5{ noexcept(S{}) };   // true; a struct's default constructor is noexcept by default
```

The `noexcept` operator can be used to conditionally execute code depending on whether it is `potentially throwing` or not. This is required to fulfill certain **exception safety guarantees**, which we’ll talk about in the next section.

noexcept操作符可以作为条件执行代码的一个判断依据，取决于这个函数到底有没有可能抛出异常。这是实现某些“异常安全保证”所必需的，我们将在下一部分中讨论。

## Exception safety guarantees

An **exception safety guarantee** is a contractual guideline about how functions or classes will behave in the event an exception occurs. There are four levels of exception safety:

**异常安全性保证**是在发生异常的情况下，关于函数或类的行为的约定的准则。有四个层次的异常安全性保证：

- No guarantee -- There are no guarantees about what will happen if an exception is thrown (e.g. a class may be left in an unusable state)

  没有保证，如果异常抛出的话，没有任何的保证

- Basic guarantee -- If an exception is thrown, no memory will be leaked and the object is still usable, but the program may be left in a modified state.

  基本的保证。如果一个异常被抛出的话，没有内存会泄露，对象仍然可用，但是程序可能处于被修改的状态。

- Strong guarantee -- If an exception is thrown, no memory will be leaked and the program state will not be changed. This means the function must either completely succeed or have no side effects if it fails. This is easy if the failure happens before anything is modified in the first place, but can also be achieved by rolling back any changes so the program is returned to the pre-failure state.

  强保证。如果异常被抛出的话，没有内存会泄露，程序的状态也不会发生变化，这意味着函数要么完全成功，要么真的一点副作用都没有。如果失败在改动之前发生，达到这样的目的是容易的。但是也可以通过回滚来使得程序达到被改动之前的状态。

- No throw / No fail -- The function will always succeed (no-fail) or fail without throwing an exception (no-throw).

  不会抛出异常，不会失败。程序总是成功，或者失败了也不抛出异常

Let’s look at the no-throw/no-fail guarantees is more detail:

我们详细看一下最后一个级别的异常安全性保证：

The `no-throw guarantee`: if a function fails, then it won’t throw an exception. Instead, it will return an error code or ignore the problem. No-throw guarantees are required during stack unwinding when an exception is already being handled; for example, all destructors should have a no-throw guarantee (as should any functions those destructors call). Examples of code that should be no-throw:

`no-throw guarantee`如果一个函数失败了的话，他不会抛出一个异常，而是会返回一个错误码或者忽略掉这个问题。（？），举个例子，所有的析构函数都应该有no-throw 保证（所有析构函数调用的函数也应该这样）。不应该抛出异常的代码示例：

- destructors and memory deallocation/cleanup functions

  析构函数和内存释放清理函数

- functions that higher-level no-throw functions need to call

  no-throw 函数要调用的那些函数

The `no-fail guarantee`: a function will always succeed in what it tries to do (and thus never has a need to throw an exception, thus, no-fail is a slightly stronger form of no-throw). Examples of code that should be no-fail:

一个函数总是会成功。不应该失败的代码示例：

- move constructors and move assignment (move semantics, covered in chapter 15)

  移动构造函数和移动赋值。

- swap functions

  交换函数

- clear/erase/reset functions on containers

  容器中的清除，擦除，重置函数

- operations on std::unique_ptr (also covered in chapter 15)

  对uniqueptr的操作

- functions that higher-level no-fail functions need to call

  nofail 函数调用的函数也不应该失败

## When to use noexcept

Just because your code doesn’t explicitly throw any exceptions doesn’t mean you should start sprinkling `noexcept` around your code. By default, most functions are `potentially throwing`, so if your function calls other functions, there is a good chance it calls a function that is `potentially throwing`, and thus is `potentially throwing` too.

不是说你的代码没有明显抛出异常，你就应该在函数签名上写一个noexcept。默认地，大部分函数都是可能抛出异常的，所以如果你的函数调用了别的函数，就有可能直接或者间接的调用了`potentially throwing`的函数，因此你的函数也成了`potentially throwing`。

The standard library’s policy is to use `noexcept` only on functions that *must not* throw or fail. Functions that are `potentially throwing` but do not actually throw exceptions (due to implementation) typically are not marked as `noexcept`.

标准库的策略是只在那些绝不应该抛出异常或者失败的函数上加noexcept。那些可能抛出异常但实际上没有抛出异常的通常也不会被标记为noexcept。

```
Best practice

Use the noexcept specifier in specific cases where you want to express a no-fail or no-throw guarantee.
把noexcept只加在你想要提供no-fail or no-throw 这样保证的函数上。
```

```
Best practice

If you are uncertain whether a function should have a no-fail/no-throw guarantee, error on the side of caution and do not mark it with noexcept. Reversing a decision to use noexcept violates an interface commitment to the user about the behavior of the function. Making guarantees stronger by retroactively adding noexcept is considered safe.
如果你不确定一个函数是不是应该拥有no-fail/no-throw的保证的时候，你就不要给它加noexcept。
```

## Why it’s useful to mark functions as non-throwing

There are a few good reasons to mark functions a non-throwing:

有几个理由：

- Non-throwing functions can be safely called from functions that are not exception-safe, such as destructors

  Non-throwing可以放心的给那些不是异常安全的函数调用，比如destructor

- Functions that are **noexcept** can enable the compiler to perform some optimizations that would not otherwise be available. Because a `noexcept` function cannot throw an exception, the compiler doesn’t have to worry about keeping the runtime stack in an unwindable state, which can allow it to produce faster code.

  noexcept的函数可以使编译器执行一些额外的优化。因为noexcept函数不会抛出异常，编译器也就不需要考虑考虑把运行栈保持在一个可以展开的状态，这样能生成更快的代码。

- There are also a few cases where knowing a function is `noexcept` allows us to produce more efficient implementations in our own code: the standard library containers (such as std::vector) are `noexcept` aware and will use the `noexcept` operator to determine whether to use `move semantics` (faster) or `copy semantics` (slower) in some places (we cover `move semantics` in chapter 15).

  知道一个函数是noexcept的话，能让我们产生更高效的实现。

## **Dynamic exception specifications**

#### Optional reading

Before C++11, and until C++17, `dynamic exception specifications` were used in place of `noexcept`. The **dynamic exception specifications** syntax uses the `throw` keyword to list which exception types a function might directly or indirectly throw:

在C++11之前，直到C++17，动态异常规范坐着noexcept位子。这个动态异常规范使用throw关键字来列出一个函数可能直接或者间接抛出的异常类型

```
int doSomething() throw(); // does not throw exceptions
int doSomething() throw(std::out_of_range, int*); // may throw either std::out_of_range or a pointer to an integer
int doSomething() throw(...); // may throw anything
```

Due to factors such as incomplete compiler implementations, some incompatibility with template functions, common misunderstandings about how they worked, and the fact that the standard library mostly didn’t use them, the dynamic exception specifications were deprecated in C++11 and removed from the language in C++17 and C++20. See [this paper](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0003r0.html#2.0) for more context.

因为各种原因，比如不完整的编译器实现，与模板函数的不匹配，关于其工作方式的常见误解，还有标准库不用这个东西的事实，这个动态异常规范在C++中被不推荐使用，然后在C++17中被删掉了。